title:
  "viaCDN"
  
description:
  "Î±lpha"

github:
  "nakedalarmclock"

social:
  links:
    - https://twitter.com/viaCDN

theme:
  jekyll-theme-cayman

permalink:
  pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
