title:
  "viaCDN Î±"
  
description:
  "alpha.viacdn.org"

github:
  "viacdn"

social:
  links:
    - https://twitter.com/viaCDN
    - https://github.com/viaCDN

theme:
  jekyll-theme-cayman

permalink:
  pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
